### ISSUE TITLE
I can't find it in right click menu where "Open editer" area and file tabpage.

### ISSUE THREAD

**Issue by shishirong** [tjx666/open-in-external-app#1]
在打开的文件夹的文件树中可以用，但在打开的编辑器和打开的文件选项卡的右键菜单没有 Open in external app 选项。

**Comment by tjx666** [comment]
@shishirong  抱歉，这么晚才看到。
其实我刚开始开发的时候就想到了这个问题，之所以没支持主要是我觉得在文件树中提供这个功能就足够了满足日常需求了。因为安装了很多的其它插件，原本编辑器右键菜单的选项就很多了，我觉得没必要加上去。
这个 issue 先挂着吧，要是反馈这个问题的人比较多我再支持。

**Comment by kanlukasz** [comment]
1. I vote for adding this option to Tabs. This can be useful because many times we don't have the file explorer open
For example - I often have git or search open instead of the file explorer
![obraz](https://user-images.githubusercontent.com/30685349/81074931-f9effc00-8ee9-11ea-8a18-21c9c23362ac.png)

2. I am against adding this to the editor area. It's rather an exaggeration

**Comment by tjx666** [comment]
@kanlukasz A new version has been released to support it

**Comment by kanlukasz** [comment]
Should this issue not be closed by now?
