### ISSUE TITLE
Set an application for all the extensions

### ISSUE THREAD

**Issue by ZacharieALES** [tjx666/open-in-external-app#15]
I would like to use emacs to open all the files (regardless of their extension). Is their a way to do that without listing all the possible extensions and associate emacs to each of them?

**Comment by tjx666** [comment]
I will implement it when I have  free time these day

**Comment by tjx666** [comment]
Upgrade to latest version and config like following:

```
"openInExternalApp.openMapper": [
        {
             "extensionName": "*",
            "apps": "emacs open command"
        }
    ]
```

**Comment by d0ob** [comment]
Hello there.

I use both VScode and VScode insider for different usage, I'd like to easily open a file in one from the other ; So I tried to configure this extension which seems perfect for that, following this topic, I tried : 

"openInExternalApp.openMapper": [
        {
            "extensionName": "*",
            "apps": [
                {
                    "title": "Visual Studio Code - Insiders",
                    "openCommand": "C:\\Users\\User\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\Code - Insiders.exe"
                }
    ]
   }
  ]
    
 (And the other way around in insider)  But nothing launch =(
 I'm afraid it simply doesn't work, because everything seems fine with notepad..
 I did something wrong ? Any clue if not ?
