### ISSUE TITLE
Doesn't work when using Windows Subsystem for Linux

### ISSUE THREAD

**Issue by hyoretsu** [tjx666/open-in-external-app#16]
I already checked and the command does work in Windows and when I run it manually on Terminal, but not when I use right-click.

**Comment by tjx666** [comment]
Need more info about how your use it.

**Comment by hyoretsu** [comment]
Right-click>Open in External App. That's it
![image](https://user-images.githubusercontent.com/20804322/132130893-b67b4d86-bb7b-4276-b623-3ea977c55dec.png)

**Comment by tjx666** [comment]
Which file type you want to open? It seems that your system has no default app to open that file type.

**Comment by hyoretsu** [comment]
Any file type, that happens on a simple .txt

**Comment by King-of-Infinite-Space** [comment]
I guess the path in WSL is treated differently in VSCode. A conversion should make it work. For example,
- File Explorer
`\\wsl.localhost\Ubuntu\path-to-folder`
- VSCode 
`vscode-remote://wsl+ubuntu/path-to-folder`

**Comment by Shengyis** [comment]
So you want to open ur file by windows app? If so, there is a way to solve it.  For example, I want to open ".lyx" files by Lyx.exe
1. put lyx.exe in windows PATH. Then I can run
```
lyx.exe
```
in Linux terminal. It should behave exactly the same as you open it on the windows side.
2.  download "code runner" extension for vscode and install it at wsl side
3.  in vscode setting, search for "Executor Map By File Extension" and add rule for ".lyx" files
```
".lyx": "cd $dir && lyx.exe $fileName &"
```
4. refresh then right click on the ".lyx" file there should be "Run Code" as the first option. "Run Code" will open the file. And you can also set shortcut for this "Run code" action. 

> Any file type, that happens on a simple .txt

**Comment by hyoretsu** [comment]
That is a workaround, yes, I use Code Runner for code files. But it still isn't a fix for this extension.

**Comment by Shengyis** [comment]
yeah...that's just an alternative way...for this extension, you can also check the setting in wsl, and add rules for your file. just like the example configuration did. But you still need to add the app to path at windows side. This is like you run
```
win-command <full-path-of-ur-file>
``` 
I only test this for lyx.exe, it does not work.......because in Linux terminal, the full path of the file starts with "/mnt/" but "lyx.exe /mnt/xxxx" actually passes "C:/mnt/xxxx" to lyx.exe then give an error.  If I use relative path in terminal then it is fine. But I did not file a way to use the relative path in this extension. Or maybe this is the problem of lyx.exe itself..Maybe you can try other windows side apps.
